### ISSUE TITLE
NB2KG fails when notebook is configured with different base_url

### ISSUE THREAD

**Issue by lresende** [jupyter-incubator/nb2kg#18]
Steps to reproduce:
 - jupyter notebook --generate-config
 - add c.NotebookApp.base_url = '/jupyter/notebook'
 - syart notebook with nb2kg pointing to a gateway

Error on console:
```
Uncaught exception GET /jupyter/notebook/api/kernelspecs (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/jupyter/notebook/api/kernelspecs', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/lresende/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/lresende/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/lresende/opensource/jupyter/nb2kg/nb2kg/handlers.py", line 324, in get
        kernel_specs = yield gen.maybe_future(ksm.list_kernel_specs())
    AttributeError: 'CondaKernelSpecManager' object has no attribute 'list_kernel_specs'
```

Note in the exception ***Uncaught exception GET /jupyter/notebook/api/kernelspecs*** that the base gateway url is being created using the notebook base url which is invalid on the gateway side.

**Comment by lresende** [comment]
Invalid, the issue was around proper registration of NB2KG on the environment I was seeing this.
